import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/cart-context";
import React from 'react';
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Celestial Threads",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${geistSans.variable} ${geistMono.variable} antialiased overflow-y-scroll`}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="#"></link>
        {/* Google Identity Services SDK */}
        <script src="https://accounts.google.com/gsi/client" async defer></script>
      </head>
      <body suppressHydrationWarning={true}>
        <React.StrictMode>
          <main className="bg-background pt-24 min-h-[calc(100vh-128px)]">
            <CartProvider>
              <AuthProvider>
                {children}
              </AuthProvider>
            </CartProvider>
          </main>
        </React.StrictMode>
      </body>
    </html>
  );
}
